### ISSUE TITLE
Convert Backing Up Your WordPress Site Lesson Plan

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/backing-up-your-wordpress-site#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/backing-up-your-wordpress-site/
